language: node_js
node_js:
- '0.11'
- '0.10'
services:
  - redis-server
before_script:
- npm install
script: "./node_modules/.bin/gulp"
after_success: ./node_modules/.bin/coveralls --verbose < output/coverage/lcov.info
